name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f852e8ce06611d3d539a1b299e85fc3e6e3400c093c31299265e28eb5299f5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
