name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "703471ffd2f7ff266a05c17b407c8e972dd461aebb6e0bfc4ac9f250c028ab90"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
