name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d772b30592b538c9bbf56158f474655e1db2309d925a7f23b3688ebb9587ad5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
