name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc713425b892d63834d84ce2a9e9fb7139447cbcc1fbb829db6699a512d1f316"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
