name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "031451b66596d6318e759771f05781d51b1ba154fcf2be223c081accbba84d91"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
