name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "791528c2d4734a1f6fec75351805854b037c81909ce6a31f6cd736afdeda59e6"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
